# Generated by Django 4.1.7 on 2023-06-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('tarih_saat', models.DateTimeField(null=True)),
                ('aciklama', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
